### ISSUE TITLE
I feel so bad for making this issue but I need to know and this seems like its the only way I can contact you. Will delete if  requested.

### ISSUE THREAD

**Issue by Cheesegriller** [Quackster/FalloutAFK#1]
I am an preservationist/archivist looking for the Roblox 2006 client. I was wondering if you are quackster from Roblox who registered in 2006 if so you might have the client on an old computer or hard drive or backup. The client is currently lost media. Please respond as soon as you can. I will delete this issue if requested. Please also consider giving me a better way to contact you if you can. Thank you.

**Comment by Quackster** [comment]
Hello, I'm sorry but I'm not the Quackster you are looking for, I've only been around since 2009 associated with Habbo Hotel private server development. Kind of a coincidence I guess, hope you find the person you're looking for, good luck. 🙂

I relate because I am a preservationist for Habbo Hotel related content.

**Comment by Cheesegriller** [comment]
That's cool dude, good luck with Habbo! Thank you.
